steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-f'
      - 'containers/docker/googlecloud/Dockerfile'  
      - '-t'
      - 'gcr.io/$PROJECT_ID/my-app'
      - '.'                                         
#dont forget to set trigger etc later im free time 
